*Anthony Vicenti*

### Overall Grade: 106/110

### Quality of report: 9/10

-   Is the homework submitted (git tag time) before deadline (Due Sep 25, 2019 @ 11:59PM)?

    No. `Thu Sep 26 04:27:59 PST`. (-1 pt)

-   Is the final report in a human readable format html? 

    Yes. `html`.

-   Is the report prepared as a dynamic document (R markdown) for better reproducibility?

    Yes. `Rmd`.

-   Is the report clear (whole sentences, typos, grammar)? Do readers have a clear idea what's going on and how are results produced by just reading the report? 

	  Yes. 
    

### Correctness and efficiency of solution: 59/60

-   Q1 (10/10)

-   Q2 (20/20)

-   Q3 (29/30)

	\#3. (-1 pt), I used `rchauchy` which should be the same as 1df T-distribution - somehow the results seems to be different. Also for tidyness consider round your results to 3 or 4 digists. 
  
    
### Usage of Git: 9/10

-   Are branches (`master` and `develop`) correctly set up? Is the hw submission put into the `master` branch?

    There is no history of `develop` branch for hw1? I saw develop branch merge for hw2. (-1 pts)

-   Are there enough commits? Are commit messages clear?  

    More than 15 commits for hw1. 
   
-   Is the hw1 submission tagged? 

    Yes. 

-   Are the folders (`hw1`, `hw2`, ...) created correctly? 

    Yes.
  
-   Do not put a lot auxiliary files into version control. 

	  No auxiliary files found.


### Reproducibility: 10/10

-   Are the materials (files and instructions) submitted to the `master` branch sufficient for reproducing all the results? Just click the `knit` button will produce the final `html` on teaching server? 

  	Yes. 
  	

-   If necessary, are there clear instructions, either in report or in a separate file, how to reproduce the results?

    Yes.

### R code style: 19/20
-   [Rule 3.](https://google.github.io/styleguide/Rguide.xml#linelength) The maximum line length is 80 characters. 


-   [Rule 4.](https://google.github.io/styleguide/Rguide.xml#indentation) When indenting your code, use two spaces.

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 

	Violation (-1 pt):
	
	- `runSim.R`: line 63, 64, 3 and `autoSim.R`: line 8, 9. 

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.).



