*Anthony Vicenti*

### Overall Grade: 103/110

### Quality of report: 10/10

-   Is the homework submitted (git tag time) before deadline (Due 11/1/2019 @ 11:59PM)? (-4 pts)

    No. `2019-11-05 14:34:57 -0700`. (shown by `git log --tags --simplify-by-decoration --pretty="format:%ci %d"`)

-   Is the final report in a human readable format html? 

    It was deployed to shinyapp.io. 

-   Is the report prepared as a dynamic document (R markdown) for better reproducibility?

    Yes. `Rmd`. But I find little documentation. 

-   Is the report clear (whole sentences, typos, grammar)? Do readers have a clear idea what's going on and how are results produced by just reading the report? (-1pt)

	  The shiny app is self-explanatory. I like your skill tab which shows the updated summary from data (not directly copied from lecture slides). But the rating tab information is not very informative - consider to include single company's rating which may be a more useful for a job applicant. 
	  
### Correctness and efficiency of solution: 59/60

-  See last comment above. 
  
    
### Usage of Git: 10/10

-   Are branches (`master` and `develop`) correctly set up? Is the hw submission put into the `master` branch?

    Yes. 

-   Are there enough commits? Are commit messages clear?  

    There are history of commits for HW2 which are good - will be even better to use informative commit messages.  
   
-   Is the hw2 submission tagged? 

    Yes. 

-   Are the folders (`hw1`, `hw2`, ...) created correctly? 

    Yes.
  
-   Do not put a lot auxiliary files into version control. 

    There are no auxiliary files in your folder. 

### Reproducibility: 10/10

-   Are the materials (files and instructions) submitted to the `master` branch sufficient for reproducing all the results? Just click the `knit` button will produce the final `html` on teaching server? 

    Yes. I can render your app using `run app` in Rstudio.   
  	

-   If necessary, are there clear instructions, either in report or in a separate file, how to reproduce the results?

    Yes. 

### R code style: 19/20
-   [Rule 3.](https://google.github.io/styleguide/Rguide.xml#linelength) The maximum line length is 80 characters. 


-   [Rule 4.](https://google.github.io/styleguide/Rguide.xml#indentation) When indenting your code, use two spaces.

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 

    `Space rule` is consistently enforced within your code. (-1pt)



