*Anthony Vicenti*

### Overall Grade: 104/110

### Quality of report: 5/10

-   Is the homework submitted (git tag time) before deadline (Due 11/27/2019 @ 11:59PM)? 

    No. `2019-12-01 21:09:19 -0700' (shown by `git log --tags --simplify-by-decoration --pretty="format:%ci %d"`) (-4)

-   Is the final report in a human readable format html? 

    Yes. `html`.

-   Is the report prepared as a dynamic document (R markdown) for better reproducibility?

    Yes. `Rmd`.

-   Is the report clear (whole sentences, typos, grammar)? Do readers have a clear idea what's going on and how are results produced by just reading the report? 

	  Yes. 
	  
### Correctness and efficiency of solution: 59/60

- I like your interesting example. It took me long time to run - given the image sizes, etc. It would be great to explore the `GPU` features through `library(cloudml)`.
- Your code also requires `library(magick)` - which seems to be a bit of work to install on linux system. 


 
### Usage of Git: 10/10

-   Are branches (`master` and `develop`) correctly set up? Is the hw submission put into the `master` branch?

    Yes.

-   Are there enough commits? Are commit messages clear?  

    Yes.   
   
-   Is the hw3 submission tagged? 

    Yes.

-   Are the folders (`hw1`, `hw2`, ...) created correctly? 

    Yes.
  
-   Do not put a lot auxiliary files into version control. 

	  There are no auxiliary files found. 


### Reproducibility: 9/10

-   Are the materials (files and instructions) submitted to the `master` branch sufficient for reproducing all the results? Just click the `knit` button will produce the final `html` on teaching server? 

   + It is always a good habit to include package installation instructions. 
  	

-   If necessary, are there clear instructions, either in report or in a separate file, how to reproduce the results?

    Yes. 

### R code style: 20/20
-   [Rule 3.](https://google.github.io/styleguide/Rguide.xml#linelength) The maximum line length is 80 characters. 


-   [Rule 4.](https://google.github.io/styleguide/Rguide.xml#indentation) When indenting your code, use two spaces.

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 




